### ISSUE TITLE
Mark support

### ISSUE THREAD

**Issue by iLexiconn** [iLexiconn/Magister.java#3]

**Comment by iLexiconn** [comment]
Closed with https://github.com/iLexiconn/Magister.java/pull/9

**Comment by KeizerDev** [comment]
@MrWolvetech, I'm getting a bug on the grades. 

This:

``` java

            System.out.println("=========== Grades ===========");
            for (Grade grade : magister.getAllGrades()){
                System.out.println(grade.course.name + ": " +grade.grade);
            }
```

Seems to reduce this:

``` java
-- Crash Log --
java.text.ParseException: String parameter was null
    at net.ilexiconn.magister.container.Appointment.appointmentDateToDate(Appointment.java:71)
    at net.ilexiconn.magister.adapter.GradeAdapter.read(GradeAdapter.java:34)
    at net.ilexiconn.magister.adapter.GradeAdapter.read(GradeAdapter.java:17)
    at com.google.gson.Gson.fromJson(Gson.java:861)
    at com.google.gson.Gson.fromJson(Gson.java:799)
    at net.ilexiconn.magister.Magister.getGrades(Magister.java:105)
    at net.ilexiconn.magister.Magister.getAllGrades(Magister.java:109)
    at net.ilexiconn.magister.Test.main(Test.java:80)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by iLexiconn** [comment]
Fixing this now
EDIT: https://github.com/iLexiconn/Magister.java/commit/5ce32f8a5b213efddcd89dd7b95d420da31512e8
