### ISSUE TITLE
Hipster crashes on Login

### ISSUE THREAD

**Issue by JWolvers** [iLexiconn/Magister.java#62]
hipster crashes on login but it appears to be a magister.java issue.

Crashlog:

```
2-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         FATAL EXCEPTION: AsyncTask #8
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         Process: net.ilexiconn.hipster, PID: 7831
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         java.lang.RuntimeException: An error occured while executing doInBackground()
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at android.os.AsyncTask$3.done(AsyncTask.java:304)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at java.lang.Thread.run(Thread.java:818)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected 1c but was 17
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.Gson.fromJson(Gson.java:873)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.Gson.fromJson(Gson.java:926)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.Gson.fromJson(Gson.java:899)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at net.ilexiconn.magister.adapter.StudyAdapter.read(StudyAdapter.java:53)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at net.ilexiconn.magister.adapter.StudyAdapter.read(StudyAdapter.java)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.Gson.fromJson(Gson.java:861)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.Gson.fromJson(Gson.java:799)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at net.ilexiconn.magister.Magister.login(Magister.java:125)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at net.ilexiconn.hipster.thread.LoginThread.doInBackground(LoginThread.java:61)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at net.ilexiconn.hipster.thread.LoginThread.doInBackground(LoginThread.java)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at android.os.AsyncTask$2.call(AsyncTask.java:292)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         ... 4 more
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         Caused by: java.lang.IllegalStateException: Expected 1c but was 17
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.android.dex.EncodedValueReader.checkType(EncodedValueReader.java:283)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.android.dex.EncodedValueReader.readArray(EncodedValueReader.java:96)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:672)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at java.lang.reflect.Field.getAnnotation(Field.java:242)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldName(ReflectiveTypeAdapterFactory.java:76)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldNames(ReflectiveTypeAdapterFactory.java:71)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:156)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.Gson.getAdapter(Gson.java:407)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.Gson.getAdapter(Gson.java:407)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.Gson.getAdapter(Gson.java:407)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
12-22 21:47:30.961 7831 8390 E     AndroidRuntime net.ilexiconn.hipster         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(Reflect
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          android.view.WindowLeaked: Activity net.ilexiconn.hipster.MainActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{63d7f1 V.E..... R......D 0,0-1336,643} that was originally added here
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.view.ViewRootImpl.<init>(ViewRootImpl.java:500)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:287)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:87)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.app.Dialog.show(Dialog.java:313)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.app.ProgressDialog.show(ProgressDialog.java:140)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.app.ProgressDialog.show(ProgressDialog.java:123)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at net.ilexiconn.hipster.thread.LoginThread.onPreExecute(LoginThread.java:51)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:591)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.os.AsyncTask.execute(AsyncTask.java:539)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at net.ilexiconn.hipster.fragment.main.tabs.settings.SettingsTabFragment$100000011$100000009.onClick(SettingsTabFragment.java:191)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:153)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.os.Handler.dispatchMessage(Handler.java:102)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.os.Looper.loop(Looper.java:145)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at android.app.ActivityThread.main(ActivityThread.java:6837)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at java.lang.reflect.Method.invoke(Native Method)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at java.lang.reflect.Method.invoke(Method.java:372)
12-22 21:47:32.211 7831 7831 E     WindowManager net.ilexiconn.hipster          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
```

**Comment by JWolvers** [comment]
Fixed it by doing a clean build, weird :/
